cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", view=views.cart_detail, name="cart_detail"),
    path("add/<int:product_line_id>", view=views.cart_add, name="cart_add"),
    path("remove/<int:product_line_id>", view=views.cart_remove, name="cart_remove"),
]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from . import views

urlpatterns = [
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    path("admin/", admin.site.urls),
    path("about/", view=views.about_us),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("users/", include("users.urls", namespace="users")),
    path("", include("products.urls", namespace="products")),
]

orders/urls.py
from django.urls import path

from . import views

app_name = "orders"

urlpatterns = [
    path("", view=views.orders_list, name="orders"),
    path("create", view=views.order_create, name="order_create"),
    path("confirm/<order_id>", view=views.order_confirmation, name="order_confirm")
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path("", views.product_list, name="products_list"),
    path("search", views.product_search, name="product_search"),
    path("<int:product_line_id>", view=views.product_detail, name="product_detail"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("sign-up/", views.sign_up, name="sign_up"),
    path("sign-in/", views.sign_in, name="sign_in"),
    path("sign-out/", views.sign_out, name="sign_out"),
]

templates/includes/footer.html
<footer class="bg-muted">
    <div class="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
        <div class="md:flex md:justify-between">
            <div class="mb-6 md:mb-0">
                <a href="https://flowbite.com/" class="flex items-center gap-2">
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                    >
                        <path
                            d="m2 7 4.41-4.41A2 2 0 0 1 7.83 2h8.34a2 2 0 0 1 1.42.59L22 7"
                        />
                        <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
                        <path d="M15 22v-4a2 2 0 0 0-2-2h-2a2 2 0 0 0-2 2v4" />
                        <path d="M2 7h20" />
                        <path
                            d="M22 7v3a2 2 0 0 1-2 2a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 16 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 12 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 8 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 4 12a2 2 0 0 1-2-2V7"
                        />
                    </svg>
                    <span
                        class="self-center whitespace-nowrap text-2xl font-semibold"
                    >
                        Shop
                    </span>
                </a>
            </div>
            <div class="grid grid-cols-2 gap-8 sm:grid-cols-3 sm:gap-6">
                <div>
                    <h2
                        class="mb-4 text-sm font-semibold uppercase"
                    >
                        Resources
                    </h2>
                    <ul class="space-y-4">
                        <li>
                            <a href="https://flowbite.com/" class="hover:underline"
                                >Flowbite</a
                            >
                        </li>
                        <li>
                            <a href="https://tailwindcss.com/" class="hover:underline"
                                >Tailwind CSS</a
                            >
                        </li>
                    </ul>
                </div>
                <div>
                    <h2
                        class="mb-4 text-sm font-semibold uppercase "
                    >
                        Follow us
                    </h2>
                    <ul class="space-y-4">
                        <li>
                            <a
                                href="https://github.com/themesberg/flowbite"
                                class="hover:underline"
                                >Github</a
                            >
                        </li>
                        <li>
                            <a
                                href="https://discord.gg/4eeurUVvTy"
                                class="hover:underline"
                                >Discord</a
                            >
                        </li>
                    </ul>
                </div>
                <div>
                    <h2
                        class="mb-4 text-sm font-semibold uppercase "
                    >
                        Legal
                    </h2>
                    <ul class="space-y-4">
                        <li>
                            <a href="#" class="hover:underline">Privacy Policy</a>
                        </li>
                        <li>
                            <a href="#" class="hover:underline">Terms &amp; Conditions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <hr class="my-6 border sm:mx-auto lg:my-8" />
        <div class="sm:flex sm:items-center sm:justify-between">
            <span class="text-sm  sm:text-center"
                >© 2023
                <a href="/" class="hover:underline">Shop™</a>.
                All Rights Reserved.
            </span>
            <div class="mt-4 flex sm:mt-0 sm:justify-center">
                <a
                    href="#"
                    class=""
                >
                    <svg
                        class="h-4 w-4"
                        aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="currentColor"
                        viewBox="0 0 8 19"
                    >
                        <path
                            fill-rule="evenodd"
                            d="M6.135 3H8V0H6.135a4.147 4.147 0 0 0-4.142 4.142V6H0v3h2v9.938h3V9h2.021l.592-3H5V3.591A.6.6 0 0 1 5.592 3h.543Z"
                            clip-rule="evenodd"
                        />
                    </svg>
                    <span class="sr-only">Facebook page</span>
                </a>
                <a
                    href="#"
                    class=" ms-5"
                >
                    <svg
                        class="h-4 w-4"
                        aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="currentColor"
                        viewBox="0 0 21 16"
                    >
                        <path
                            d="M16.942 1.556a16.3 16.3 0 0 0-4.126-1.3 12.04 12.04 0 0 0-.529 1.1 15.175 15.175 0 0 0-4.573 0 11.585 11.585 0 0 0-.535-1.1 16.274 16.274 0 0 0-4.129 1.3A17.392 17.392 0 0 0 .182 13.218a15.785 15.785 0 0 0 4.963 2.521c.41-.564.773-1.16 1.084-1.785a10.63 10.63 0 0 1-1.706-.83c.143-.106.283-.217.418-.33a11.664 11.664 0 0 0 10.118 0c.137.113.277.224.418.33-.544.328-1.116.606-1.71.832a12.52 12.52 0 0 0 1.084 1.785 16.46 16.46 0 0 0 5.064-2.595 17.286 17.286 0 0 0-2.973-11.59ZM6.678 10.813a1.941 1.941 0 0 1-1.8-2.045 1.93 1.93 0 0 1 1.8-2.047 1.919 1.919 0 0 1 1.8 2.047 1.93 1.93 0 0 1-1.8 2.045Zm6.644 0a1.94 1.94 0 0 1-1.8-2.045 1.93 1.93 0 0 1 1.8-2.047 1.918 1.918 0 0 1 1.8 2.047 1.93 1.93 0 0 1-1.8 2.045Z"
                        />
                    </svg>
                    <span class="sr-only">Discord community</span>
                </a>
                <a
                    href="#"
                    class=" ms-5 "
                >
                    <svg
                        class="h-4 w-4"
                        aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="currentColor"
                        viewBox="0 0 20 17"
                    >
                        <path
                            fill-rule="evenodd"
                            d="M20 1.892a8.178 8.178 0 0 1-2.355.635 4.074 4.074 0 0 0 1.8-2.235 8.344 8.344 0 0 1-2.605.98A4.13 4.13 0 0 0 13.85 0a4.068 4.068 0 0 0-4.1 4.038 4 4 0 0 0 .105.919A11.705 11.705 0 0 1 1.4.734a4.006 4.006 0 0 0 1.268 5.392 4.165 4.165 0 0 1-1.859-.5v.05A4.057 4.057 0 0 0 4.1 9.635a4.19 4.19 0 0 1-1.856.07 4.108 4.108 0 0 0 3.831 2.807A8.36 8.36 0 0 1 0 14.184 11.732 11.732 0 0 0 6.291 16 11.502 11.502 0 0 0 17.964 4.5c0-.177 0-.35-.012-.523A8.143 8.143 0 0 0 20 1.892Z"
                            clip-rule="evenodd"
                        />
                    </svg>
                    <span class="sr-only">Twitter page</span>
                </a>
                <a
                    href="#"
                    class="ms-5"
                >
                    <svg
                        class="h-4 w-4"
                        aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="currentColor"
                        viewBox="0 0 20 20"
                    >
                        <path
                            fill-rule="evenodd"
                            d="M10 .333A9.911 9.911 0 0 0 6.866 19.65c.5.092.678-.215.678-.477 0-.237-.01-1.017-.014-1.845-2.757.6-3.338-1.169-3.338-1.169a2.627 2.627 0 0 0-1.1-1.451c-.9-.615.07-.6.07-.6a2.084 2.084 0 0 1 1.518 1.021 2.11 2.11 0 0 0 2.884.823c.044-.503.268-.973.63-1.325-2.2-.25-4.516-1.1-4.516-4.9A3.832 3.832 0 0 1 4.7 7.068a3.56 3.56 0 0 1 .095-2.623s.832-.266 2.726 1.016a9.409 9.409 0 0 1 4.962 0c1.89-1.282 2.717-1.016 2.717-1.016.366.83.402 1.768.1 2.623a3.827 3.827 0 0 1 1.02 2.659c0 3.807-2.319 4.644-4.525 4.889a2.366 2.366 0 0 1 .673 1.834c0 1.326-.012 2.394-.012 2.72 0 .263.18.572.681.475A9.911 9.911 0 0 0 10 .333Z"
                            clip-rule="evenodd"
                        />
                    </svg>
                    <span class="sr-only">GitHub account</span>
                </a>
                <a
                    href="#"
                    class=" ms-5 "
                >
                    <svg
                        class="h-4 w-4"
                        aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="currentColor"
                        viewBox="0 0 20 20"
                    >
                        <path
                            fill-rule="evenodd"
                            d="M10 0a10 10 0 1 0 10 10A10.009 10.009 0 0 0 10 0Zm6.613 4.614a8.523 8.523 0 0 1 1.93 5.32 20.094 20.094 0 0 0-5.949-.274c-.059-.149-.122-.292-.184-.441a23.879 23.879 0 0 0-.566-1.239 11.41 11.41 0 0 0 4.769-3.366ZM8 1.707a8.821 8.821 0 0 1 2-.238 8.5 8.5 0 0 1 5.664 2.152 9.608 9.608 0 0 1-4.476 3.087A45.758 45.758 0 0 0 8 1.707ZM1.642 8.262a8.57 8.57 0 0 1 4.73-5.981A53.998 53.998 0 0 1 9.54 7.222a32.078 32.078 0 0 1-7.9 1.04h.002Zm2.01 7.46a8.51 8.51 0 0 1-2.2-5.707v-.262a31.64 31.64 0 0 0 8.777-1.219c.243.477.477.964.692 1.449-.114.032-.227.067-.336.1a13.569 13.569 0 0 0-6.942 5.636l.009.003ZM10 18.556a8.508 8.508 0 0 1-5.243-1.8 11.717 11.717 0 0 1 6.7-5.332.509.509 0 0 1 .055-.02 35.65 35.65 0 0 1 1.819 6.476 8.476 8.476 0 0 1-3.331.676Zm4.772-1.462A37.232 37.232 0 0 0 13.113 11a12.513 12.513 0 0 1 5.321.364 8.56 8.56 0 0 1-3.66 5.73h-.002Z"
                            clip-rule="evenodd"
                        />
                    </svg>
                    <span class="sr-only">Dribbble account</span>
                </a>
            </div>
        </div>
    </div>
</footer>

templates/includes/form.html
{% if form %}
    <form
            action="{{ action }}{% if next %}?next={{ next }}{% endif %}"
            method="post"
            class="form"
        >
            {% csrf_token %}

            {% if form.non_field_errors %}
                <ol class="list-disc text-sm text-destructive">
                    {% for error in form.non_field_errors %}
                        <li><strong>{{ error|escape }}</strong></li>
                    {% endfor %}
                </ol>
            {% endif %}
            
            {% for field in form %}
                <div class="form-item">
                    {% if field.field.widget.input_type == 'checkbox' %}
                        {{ field }}
                        {{ field.label_tag }}
                    {% else %}
                        {{ field.label_tag }}
                        {{ field }}
                    {% endif %}
                   
                    {% if field.help_text %}
                        <p class="form-description" id="{{ field.auto_id }}_helptext">
                            {{ field.help_text|safe }}
                        </p>
                    {% endif %}
                    {% if field.errors %}
                        <ol class=" text-sm list-disc text-destructive">
                        {% for error in field.errors %}
                            <li><strong>{{ error|escape }}</strong></li>
                        {% endfor %}
                        </ol>
                    {% endif %}
                </div>
            {% endfor %}
            <button class="btn btn-size btn-primary">
                {{ btn_label }}
            </button>
        </form>
{% endif %}

templates/includes/navbar.html
<header
    class="bg-background container sticky top-0 z-50 flex gap-10 h-14 items-center justify-between border-b"
>
    <a href="/" class="flex items-center gap-1.5">
        <svg 
            xmlns="http://www.w3.org/2000/svg" 
            width="24" 
            height="24" 
            viewBox="0 0 24 24" 
            fill="none" 
            stroke="currentColor" 
            stroke-width="2" 
            stroke-linecap="round" 
            stroke-linejoin="round" 
            class="lucide lucide-store"
        >
            <path d="m2 7 4.41-4.41A2 2 0 0 1 7.83 2h8.34a2 2 0 0 1 1.42.59L22 7"/>
            <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"/>
            <path d="M15 22v-4a2 2 0 0 0-2-2h-2a2 2 0 0 0-2 2v4"/>
            <path d="M2 7h20"/>
            <path d="M22 7v3a2 2 0 0 1-2 2a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 16 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 12 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 8 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 4 12a2 2 0 0 1-2-2V7"/>
        </svg>

        <span class="font-chewy whitespace-nowrap text-lg font-medium"> Shop </span>
    </a>
    <nav class="max-md:hidden flex grow justify-center gap-x-6">
        <a
            href="/"
            class="{% if request.path == '/' %}underline font-medium{% endif%} underline-offset-4"
            >
            Home
        </a>
        <a
            href="/"
            class="{% if request.path == '/contact/' %}underline font-medium{% endif%} underline-offset-4"
            >
            Contact
        </a>
        <a
            href="/about/"
            class="{% if request.path == '/about/' %}underline font-medium{% endif%} underline-offset-4"
            >
            About
        </a>

        {% if not user.is_authenticated %}
            <a
                href="{% url "users:sign_in" %}"
                class="{% if request.path == '/sign-in/' %}underline font-medium{% endif%} underline-offset-4"
                >
                Sign in
            </a>
            <a
                href="{% url "users:sign_up" %}"
                class="{% if request.path == '/users/sign-up/' %}underline font-medium{% endif%} underline-offset-4"
                >
                Sign up
            </a>
        {% endif %}
        
    </nav>
    <div class="flex sm:grow md:grow-0 gap-6 items-center">
        <search class="grow max-sm:hidden">
            <form action="{% url "products:product_search" %}" class='relative bg-muted/85 rounded'>
                <input
                    type="search"
                    name="term"
                    value="{% if term %}{{ term }}{% endif %}"
                    placeholder="What are you looking for?"
                    class="peer flex w-full rounded border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                    aria-label="Search"
                    aria-describedby="search-description"
                    autocomplete="off"
                    spellcheck="false"
                    inputmode="search"
                    minlength="1"
                    maxlength="256"
                    pattern=".*\S.*"
                    required
                    role="searchbox"
                />

              
                <svg 
                    xmlns="http://www.w3.org/2000/svg" 
                    width="16" 
                    height="16" 
                    viewBox="0 0 24 24" 
                    fill="none" 
                    stroke="currentColor" 
                    stroke-width="2" 
                    stroke-linecap="round" 
                    stroke-linejoin="round" 
                    class="hidden absolute right-2 top-1/2 -translate-y-1/2 transition-opacity peer-placeholder-shown:inline pointer-events-none"
                    aria-hidden
                >
                    <circle cx="11" cy="11" r="8" />
                    <path d="m21 21-4.3-4.3" />
                </svg>
            </form>
        </search>
        <div class="flex gap-2">
            <button class="btn  btn-icon">
                <span class="sr-only">See you favourates</span>
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    >
                    <path
                        d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"
                    />
                </svg>
            </button>
            <a href="{% url "cart:cart_detail" %}" class="btn  btn-icon">
                <span class="sr-only">Cart</span>
                <div class="relative">
                    {% if cart and request.path != "/cart/" %}
                        <span class="size-4 flex items-center justify-center text-xs bg-destructive text-destructive-foreground font-medium rounded-full absolute -top-1/2 translate-y-1/2 left-full -translate-x-1/2">{{ cart.get_total_items }}</span>
                    {% endif %}
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        fill="{% if request.path == "/cart/" %}black{% else %}none{% endif %}"
                        stroke="black"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        >
                            <circle
                                cx="8"
                                cy="21"
                                r="1"
                            />
                            <circle
                                cx="19"
                                cy="21"
                                r="1"
                            />
                            <path
                                d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12"
                            />
                        </svg>
                </div>
            </a>
            <button
                data-collapse-toggle="navbar-default"
                type="button"
                class="btn btn-icon md:hidden"
                aria-controls="navbar-default"
                aria-expanded="false"
            >
                <span class="sr-only">Open main menu</span>
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="lucide lucide-menu">
                    <line x1="4" x2="20" y1="12" y2="12"/>
                    <line x1="4" x2="20" y1="6" y2="6"/>
                    <line x1="4" x2="20" y1="18" y2="18"/>
                </svg>
            </button>

            {% if user.is_authenticated %}
                <button 
                    id="dropdownUserAvatarButton" 
                    data-dropdown-toggle="dropdownAvatar" 
                    type="button"
                    class="btn btn-icon"
                >
                    <span class="sr-only">Open user menu</span>
                    <svg 
                        xmlns="http://www.w3.org/2000/svg" 
                        width="24"
                        height="24" 
                        viewBox="0 0 24 24" 
                        fill="none" 
                        stroke="currentColor" 
                        stroke-width="2" 
                        stroke-linecap="round" 
                        stroke-linejoin="round" 
                        class="lucide lucide-user">
                        <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/>
                        <circle cx="12" cy="7" r="4"/>
                    </svg>
                </button>

                
                <div 
                    id="dropdownAvatar" 
                    class="z-10 hidden bg-popover text-popover-foreground divide-y divide-y-muted rounded-lg shadow w-44">
                    <div class="px-4 py-3 text-sm">
                        <p>{{ user.get_full_name }}</p>
                        <p class="font-light text-muted-foreground truncate">{{ user.email }}</p>
                    </div>
                    <ul 
                        class="py-2 text-sm" 
                        aria-labelledby="dropdownUserAvatarButton">
                        <li>
                            <a 
                                href="{% url "orders:orders" %}" 
                                class="block px-4 py-2 hover:bg-muted">
                                Orders
                            </a>
                        </li>
                        <li>
                            <a href="#" class="block px-4 py-2 hover:bg-muted">Dashboard</a>
                        </li>
                        <li>
                            <a href="#" class="block px-4 py-2 hover:bg-muted">Settings</a>
                        </li>
                        <li>
                            <a href="#" class="block px-4 py-2 hover:bg-muted">Earnings</a>
                        </li>
                    </ul>
                    <form 
                        action="{% url "users:sign_out" %}" 
                        method="post"
                        class="py-2"
                        >
                        {% csrf_token %}
                        
                        <button class="text-left px-4 py-2 text-sm hover:bg-muted">
                            Sign out
                        </button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
</header>